substitutions:
  device_name: tclac
  humanly_name: TCL Air Conditioner Badroom
  wifi_ssid: "TPLink62"
  wifi_password: "69096860"
  recovery_pass: mKSzmBdt7DAj
  ota_pass: 90cf525a594c8bb2cbf917bc2c2fa058
  api_key: cSFfEIavDEIL7kpZGg24Emr2guifgYPv2HlGN4V4AsM=
  uart_rx: GPIO3
  uart_tx: GPIO1
  receive_led: GPIO2
  transmit_led: GPIO2

packages:
  remote_package:
    url: https://github.com/linkevich-vladimir/tclac.git
    ref: master
    files:
      - packages/core.yaml
    refresh: 30s

esp32:
  board: nodemcu-32s
  framework:
    type: arduino
